version: '3.8'

services:
  # Web server with Apache and PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: VC-web
    networks:
      - sims-net
    ports:
      - "8080:80"
    volumes:
      - ../public_html:/var/www/html
      - ../config:/var/www/html/config
    depends_on:
      - mariadb
      - mongodb
    environment:
      - DB_HOST=mariadb
      - DB_USER=simsuser
      - DB_PASS=Putamare123
      - DB_NAME=simsdb
    restart: unless-stopped

  # MariaDB database
  mariadb:
    image: mariadb:latest
    container_name: VC-mariadb
    networks:
      - sims-net
    environment:
      MYSQL_ROOT_PASSWORD: Putamare123.
      MYSQL_DATABASE: simsdb
      MYSQL_USER: simsuser
      MYSQL_PASSWORD: Putamare123
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init/mariadb-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pPutamare123."]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: VC-mongodb
    networks:
      - sims-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: simsadmin
      MONGO_INITDB_ROOT_PASSWORD: Putamare123.
      MONGO_INITDB_DATABASE: simsdb
    volumes:
      - mongodb_data:/data/db
      - ./init/mongodb-init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      
  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: VC-phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: simsuser
      PMA_PASSWORD: Putamare123
    ports:
      - "8081:80"
    networks:
      - sims-net
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: VC-phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: simsuser
      PMA_PASSWORD: Putamare123
    ports:
      - "8081:80"
    networks:
      - sims-net
    restart: unless-stopped

networks:
  sims-net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local